# 1.Print 'Hello HCIA'.

In [70]:
print ('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [11]:
a = 3
b = 4
S = a + b
print (S)

7


# 3.Define a list and replicate in three different ways.

In [32]:
a = [1, 3, 6, 9]
c = list(a)
k = len(a)
d = []
for i in range (0,k):
    d.append(a.pop(0))
b = c
print (b)
print (c)
print (d)

[1, 3, 6, 9]
[1, 3, 6, 9]
[1, 3, 6, 9]


# 4.Define two lists and merge them together.

In [18]:
a = [1, 2, 3]
b = [4, 5, 6]
c = a + b
print(c)

[1, 2, 3, 4, 5, 6]


# 5. Get the last element of the list and print it.

In [6]:
c = [6, 7, 9]
print(c.pop())

9


# 6.Define a tuple that contains only one element.

In [12]:
a = ('k')
print (a)

k


# 7.Define a three-line long string.

In [25]:
s = """        very
        long 
        string"""
print (s)

        very
        long 
        string


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [35]:
a = tuple('hello, world!')
k = len(a)
for i in range (0, k):
    print(a[i])

h
e
l
l
o
,
 
w
o
r
l
d
!


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [69]:
def Mul(x, y):
    return x * y
a = 9
b = 8
print(Mul(a,b))

72


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [41]:
import numpy
c = numpy.zeros((5,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [72]:
import numpy
c = numpy.zeros((4,6))
print(c)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [43]:
import numpy
a = numpy.arange(15)
b = numpy.zeros((3,5))
a = a.reshape(b.shape)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [67]:
import numpy
a = numpy.matrix('[1, 2; 3, 4]')
b = numpy.matrix('[5, 6; 7, 8]')
c = numpy.matmul(a, b)
print(c)

[[19 22]
 [43 50]]
